# Generated by Django 4.0 on 2022-01-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('fee', models.FloatField()),
                ('sub1', models.CharField(max_length=100)),
            ],
        ),
    ]
